### ISSUE TITLE
No module named 'pydot'

### ISSUE THREAD

**Issue by NeveIsa** [mackncheesiest/heft#16]
Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
Python 3.9, on running `python -m heft.heft --showDAG`

We get 

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sampad/Desktop/heft/heft/heft.py", line 455, in <module>
    dag = readDagMatrix(args.dag_file, args.showDAG) 
  File "/home/sampad/Desktop/heft/heft/heft.py", line 413, in readDagMatrix
    nx.draw(dag, pos=nx.nx_pydot.graphviz_layout(dag, prog='dot'), with_labels=True)
  File "/home/sampad/.local/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 257, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "/home/sampad/.local/lib/python3.9/site-packages/networkx/drawing/nx_pydot.py", line 298, in pydot_layout
    import pydot
ModuleNotFoundError: No module named 'pydot'

**Comment by NeveIsa** [comment]
It worked after installing pydot via `pip install pydot`

Just for reference, I was also missing graphviz which I installed using `pacman -S graphviz`.

**Comment by mackncheesiest** [comment]
That's strange, did you run `pip install -r requirements.txt` before running? That process is supposed to install [`pydot==1.4.1`](https://github.com/mackncheesiest/heft/blob/e263a7659cea0e74ceaea83e43d4ae9292bcfb07/requirements.txt#L4)
